language: cpp
os:
  - linux
compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe multiverse"
  - sudo apt-get update

install:
  - sudo apt-get install libpango-1.0-0 libpangocairo-1.0-0	
  - sudo apt-get install --no-install-recommends g++ gnuplot-nox python-gnuplot python-tk python-matplotlib python-scipy python-pytest libblitz0-dev cmake libboost-python-dev libthrust-dev 

script:

  # install libcloudphxx in Release mode
  - cd ..
  - git clone --depth=1 git://github.com/igfuw/libcloudphxx.git
  - cd libcloudphxx
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
  - make
  - sudo make install
  - cd ../..

  # run parcel tests (unit and long) TODO
  - cd parcel
  - py.test unit_test/
